env:
  - SPEC=linux-g++    VARIANT=debug_and_release   QMAKE_EXTRA=""
  - SPEC=linux-clang  VARIANT=debug_and_release   QMAKE_EXTRA=""
  - SPEC=linux-g++    VARIANT=debug_and_release   QMAKE_EXTRA="DEFINES += REFLECT_MACRO_IMPL"
  - SPEC=linux-clang  VARIANT=debug_and_release   QMAKE_EXTRA="DEFINES += REFLECT_MACRO_IMPL"

install:
  - sudo add-apt-repository --yes ppa:arigy/xfce
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update
  - sudo apt-get install qt5-default clang
  - cd test
  - qmake -spec ${SPEC} "CONFIG += ${VARIANT}\n${QMAKE_EXTRA}"

script:
  - make check