env:
  - SPEC=linux-g++
  - SPEC=linux-clang
  - VARIANT=debug
  - VARIANT=release

install:
  - sudo add-apt-repository --yes ppa:arigy/xfce
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update
  - sudo apt-get install qt5-default clang libc6-dev
  - cd test
  - qmake -spec ${SPEC} "CONFIG += ${VARIANT}"

script:
  - make check